"""Credentials, Access Control, Rate Limiting, and Tool Authorization package for Buddy Agent."""

from agent.credy.ratelimiting import (
    DEFAULT_AGENT_RATE_LIMITS,
    DEFAULT_FALLBACK_LIMIT,
    RateLimitExceededError,
    RateLimitTracker,
    RateLimiterHook,
    rate_limiter,
)
from agent.credy.rbac import (
    AGENT_ROLE_MAPPING,
    BENJAMIN_USER,
    GUEST_USER,
    ROLE_PERMISSIONS,
    RBACHook,
    RBACAccessDeniedError,
    RBACManager,
    Role,
    User,
    rbac_manager,
)
from agent.credy.tool_allowed import (
    AGENT_ALLOWED_TOOLS_MAP,
    API_MANAGER_ALLOWED_TOOLS,
    BUDDY_ALLOWED_TOOLS,
    DANGEROUS_TOOLS,
    DEFAULT_AUTO_APPROVED_TOOLS,
    DELEGATION_TOOLS,
    GITHUB_ALLOWED_TOOLS,
    GITHUB_TOOLS,
    MEMORY_TOOLS,
    REST_AGENT_ALLOWED_TOOLS,
    SAM_CLI_ALLOWED_TOOLS,
    SAM_CLI_TOOLS,
    SKILL_TOOLS,
    TEXT_EDITOR_SAFE_TOOLS,
    ToolAllowedHook,
    filter_agent_tools,
    get_allowed_tools_for_agent,
    is_auto_approved,
    is_tool_allowed,
)

__all__ = [
    # Rate Limiting
    "DEFAULT_AGENT_RATE_LIMITS",
    "DEFAULT_FALLBACK_LIMIT",
    "RateLimitExceededError",
    "RateLimitTracker",
    "RateLimiterHook",
    "rate_limiter",
    # RBAC
    "Role",
    "User",
    "BENJAMIN_USER",
    "GUEST_USER",
    "AGENT_ROLE_MAPPING",
    "ROLE_PERMISSIONS",
    "RBACAccessDeniedError",
    "RBACManager",
    "rbac_manager",
    "RBACHook",
    # Tool Permissions & Whitelisting
    "DELEGATION_TOOLS",
    "SKILL_TOOLS",
    "GITHUB_TOOLS",
    "MEMORY_TOOLS",
    "SAM_CLI_TOOLS",
    "TEXT_EDITOR_SAFE_TOOLS",
    "DANGEROUS_TOOLS",
    "DEFAULT_AUTO_APPROVED_TOOLS",
    "BUDDY_ALLOWED_TOOLS",
    "API_MANAGER_ALLOWED_TOOLS",
    "SAM_CLI_ALLOWED_TOOLS",
    "GITHUB_ALLOWED_TOOLS",
    "REST_AGENT_ALLOWED_TOOLS",
    "AGENT_ALLOWED_TOOLS_MAP",
    "get_allowed_tools_for_agent",
    "is_tool_allowed",
    "is_auto_approved",
    "filter_agent_tools",
    "ToolAllowedHook",
]
